name: Mirror FTP server

on:
  workflow_dispatch:
    inputs:
      clean:
        description: Remove old files
        required: false

jobs:
  mirror:
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email '121622595+jeroen[bot]@users.noreply.github.com'
          git config --global user.name  'Jeroen (via CI)'
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git
          update: false
      - name: Mirror files
        run: ./mirror.sh
        env:
          CLEAN: ${{ github.event.inputs.clean }}
        shell: msys2 {0}
      - name: Push binaries
        run: |
          git add mirrors mingw32 mingw64 ucrt64 dates.txt
          git commit -m "Mirror update ($(date +%F))" || exit 0
          git push origin master
        shell: bash
